<a href="https://colab.research.google.com/github/SameerPasha565/Air-pollution-analysis/blob/main/Prac1Assignment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
! git config --global user.name "sameerpasha565"

In [2]:
! git config --global user.email "sameerpasha565@gmail.com"

In [5]:
username = "sameerpasha565"
repo = "Air-pollution-analysis"

In [6]:
! git clone https://@github.com/{username}/{repo}

Cloning into 'Air-pollution-analysis'...
warning: redirecting to https://github.com/sameerpasha565/Air-pollution-analysis/
remote: Enumerating objects: 17, done.
remote: Counting objects: 100% (17/17), done.
remote: Compressing objects: 100% (17/17), done.
remote: Total 17 (delta 4), reused 0 (delta 0), pack-reused 0 (from 0)
Receiving objects: 100% (17/17), 5.72 MiB | 6.66 MiB/s, done.
Resolving deltas: 100% (4/4), done.

In [9]:
%cd {repo}

/content/Air-pollution-analysis

In [4]:
import pandas as pd
import glob

In [7]:
StationData_files = glob.glob("*20170228.csv")

In [8]:
All_Station_data = []

for file_name in StationData_files:
    city_df = pd.read_csv(file_name)

    All_Station_data.append(city_df)

    print(f"Loaded: {file_name}")

combined_data = pd.concat(All_Station_data, ignore_index=True)

combined_data.to_csv("All_Station_data_combined.csv", index=False)

print(f"SUCCESS: Combined {len(All_Station_data)} files into one file with {len(combined_data)} total rows")
print("The combined file is saved as: All_Station_data_combined.csv")

Loaded: PRSA_Data_Changping_20130301-20170228.csv
Loaded: PRSA_Data_Dongsi_20130301-20170228.csv
Loaded: PRSA_Data_Huairou_20130301-20170228.csv
Loaded: PRSA_Data_Gucheng_20130301-20170228.csv
SUCCESS: Combined 4 files into one file with 140256 total rows
The combined file is saved as: All_Station_data_combined.csv

In [10]:
df= pd.read_csv('All_Station_data_combined.csv')
df

,No,year,month,day,hour,PM2.5,PM10,SO2,NO2,CO,O3,TEMP,PRES,DEWP,RAIN,wd,WSPM,station
0,1,2013,3,1,0,3.0,6.0,13.0,7.0,300.0,85.0,-2.3,1020.8,-19.7,0.0,E,0.5,Changping
1,2,2013,3,1,1,3.0,3.0,6.0,6.0,300.0,85.0,-2.5,1021.3,-19.0,0.0,ENE,0.7,Changping
2,3,2013,3,1,2,3.0,3.0,22.0,13.0,400.0,74.0,-3.0,1021.3,-19.9,0.0,ENE,0.2,Changping
3,4,2013,3,1,3,3.0,6.0,12.0,8.0,300.0,81.0,-3.6,1021.8,-19.1,0.0,NNE,1.0,Changping
4,5,2013,3,1,4,3.0,3.0,14.0,8.0,300.0,81.0,-3.5,1022.3,-19.4,0.0,N,2.1,Changping
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
140251,35060,2017,2,28,19,14.0,58.0,4.0,19.0,500.0,56.0,12.8,1009.9,-17.0,0.0,NNW,3.1,Gucheng
140252,35061,2017,2,28,20,27.0,83.0,6.0,60.0,700.0,26.0,11.1,1010.4,-15.5,0.0,NW,1.9,Gucheng
140253,35062,2017,2,28,21,22.0,37.0,7.0,52.0,600.0,27.0,10.5,1010.8,-15.9,0.0,N,2.3,Gucheng
140254,35063,2017,2,28,22,9.0,23.0,3.0,13.0,400.0,57.0,8.9,1010.9,-14.9,0.0,NE,1.6,Gucheng
140255,35064,2017,2,28,23,12.0,48.0,5.0,48.0,600.0,28.0,6.2,1010.5,-13.4,0.0,NNE,0.7,Gucheng

In [12]:
df.shape

(140256, 18)

In [14]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 140256 entries, 0 to 140255
Data columns (total 18 columns):
 #   Column   Non-Null Count   Dtype
---  ------   --------------   -----
 0   No       140256 non-null  int64
 1   year     140256 non-null  int64
 2   month    140256 non-null  int64
 3   day      140256 non-null  int64
 4   hour     140256 non-null  int64
 5   PM2.5    137133 non-null  float64
 6   PM10     137963 non-null  float64
 7   SO2      137478 non-null  float64
 8   NO2      135681 non-null  float64
 9   CO       132715 non-null  float64
 10  O3       137108 non-null  float64
 11  TEMP     140081 non-null  float64
 12  PRES     140083 non-null  float64
 13  DEWP     140079 non-null  float64
 14  RAIN     140087 non-null  float64
 15  wd       139577 non-null  object
 16  WSPM     140108 non-null  float64
 17  station  140256 non-null  object
dtypes: float64(11), int64(5), object(2)
memory usage: 19.3+ MB

In [16]:
df.describe().T

,count,mean,std,min,25%,50%,75%,max
No,140256.0,17532.500000,10122.141000,1.0000,8766.75,17532.5,26298.25,35064.0
year,140256.0,2014.662560,1.177201,2013.0000,2014.00,2015.0,2016.00,2017.0
month,140256.0,6.522930,3.448715,1.0000,4.00,7.0,10.00,12.0
day,140256.0,15.729637,8.800123,1.0000,8.00,16.0,23.00,31.0
hour,140256.0,11.500000,6.922211,0.0000,5.75,11.5,17.25,23.0
PM2.5,137133.0,77.710890,78.870131,2.0000,20.00,53.0,108.00,882.0
PM10,137963.0,103.875539,91.413296,2.0000,35.00,81.0,145.00,999.0
SO2,137478.0,15.251698,21.170256,0.2856,2.00,7.0,19.00,500.0
NO2,135681.0,46.614027,33.168157,1.0265,21.00,39.0,66.00,276.0
CO,132715.0,1205.641322,1113.658619,100.0000,500.00,900.0,1500.00,10000.0
O3,137108.0,58.161796,56.027880,0.2142,14.00,46.0,82.00,1071.0
TEMP,140081.0,13.416940,11.482080,-19.9000,3.00,14.4,23.10,41.6
PRES,140083.0,1009.184718,10.349554,982.4000,1000.80,1008.8,1017.30,1042.0
DEWP,140079.0,2.200587,13.873769,-43.4000,-9.40,2.6,15.00,29.1
RAIN,140087.0,0.064194,0.807661,0.0000,0.00,0.0,0.00,52.1
WSPM,140108.0,1.677524,1.254475,0.0000,0.90,1.3,2.10,12.9

In [19]:
df.isnull().sum()

No            0
year          0
month         0
day           0
hour          0
PM2.5      3123
PM10       2293
SO2        2778
NO2        4575
CO         7541
O3         3148
TEMP        175
PRES        173
DEWP        177
RAIN        169
wd          679
WSPM        148
station       0
dtype: int64